apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - image: busybox
    name: writer
    command: ['sh', '-c', 'while true; do echo Success! >> /output/log.txt; sleep 5; done']
    volumeMounts:
    - mountPath: /output
      name: log-volume
  - image: busybox
    name: reader
    command: ['sh', '-c', 'sleep 5; tail -f /input/log.txt']
    volumeMounts:
    - mountPath: /input
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}