apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expandable
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: expandable-pv
spec:
  storageClassName: expandable
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/output
  persistentVolumeReclaimPolicy: Recycle
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: expandable
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: host-logs
spec:
  containers:
  - image: busybox
    name: logger
    command: ['sh', '-c', 'while true; do echo Success! >> /output/output.txt; sleep 5; done']
    volumeMounts:
    - mountPath: /output
      name: log-volume
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: my-pvc